###THIS information should match with the information listed at
###    https://wiki.movenetworks.com/display/RSCLOUD/Deployment+Notes+And+Status#DeploymentNotesAndStatus-BETArsdvr-beta

#TODO: Allow this information to be updated based on a simple webscrape of the above URL
Setups:

  Node User Recordings:
   api call:
    User Recordings Ribbon:
     1:
      norm_lower: 30
      norm_upper: 50
      optional_fields: {}
      weight: 1
      size: 50
   env: DEV2
   node: 1
   version: 1
   min: 45
   max: 50

  VIP User Recordings:
    api call:
      User Recordings Ribbon:
        1:
          norm_lower: 30
          norm_upper: 50
          optional_fields: {}
          weight: 1
          size: 50
    env: DEV2
    node: 1
    version: 1
    min: 45
    max: 50

  Node Network:
    api call:
      Basic Network: {}
    env: DEV2
    node: 1
    min: 45
    max: 50

  VIP Network:
    api call:
      Basic Network: {}
    env: DEV2
    node: 1
    min: 45
    max: 50


Procedures:


  VIP To Failure:
    -
      init user count: 0
      final user count: 800
      hatch rate: 40
      time at load: 0
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 800
      final user count: 2000
      hatch rate: 1
      time at load: 0
      fresh procedure stats: false
      ramp up stats seperate: false

  Node To Failure:
    -
      init user count: 0
      final user count: 150
      hatch rate: 8
      time at load: 0
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 150
      final user count: 500
      hatch rate: .333
      time at load: 0
      fresh procedure stats: false
      ramp up stats seperate: false


  Node Benchmark:
    -
      init user count: 0
      final user count: 200
      hatch rate: 10
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 200
      final user count: 280
      hatch rate: 10
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 200
      final user count: 280
      hatch rate: 0
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false

  VIP Benchmark:
    -
      init user count: 0
      final user count: 1200
      hatch rate: 60
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 1200
      final user count: 1680
      hatch rate: 60
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 1680
      final user count: 1200
      hatch rate: 0
      time at load: 30
      fresh procedure stats: false
      ramp up stats seperate: false



  Node Soak:
    -
      init user count: 0
      final user count: 150
      hatch rate: 2
      time at load:
      fresh procedure stats: false
      ramp up stats seperate: true

  VIP Soak:
    -
      init user count: 0
      final user count: 600
      time at load:
      fresh procedure stats: false
      ramp up stats seperate: true


  Node Fail Over:
    -
      init user count: 0
      final user count: 1000
      hatch rate: .5
      time at load: 0
      fresh procedure stats: false



  VIP Fail Over:
    -
      init user count: 0
      final user count: 3000
      hatch rate: .5
      time at load: 0
      fresh procedure stats: false





  Test Level Platue Level Back Down:
    -
      init user count: 0
      final user count: 200
      hatch rate: 30
      time at load: .5
      fresh procedure stats: false
      ramp up stats seperate: false
    -
      init user count: 200
      final user count: 280
      hatch rate: 10
      time at load: .5
      fresh procedure stats: false
      ramp up stats seperate: true
    -
      init user count: 280
      final user count: 350
      hatch rate: 1
      time at load: .5
      fresh procedure stats: true
      ramp up stats seperate: false
    -
      init user count: 350
      final user count: 200
      hatch rate: 1
      time at load: .5
      fresh procedure stats: true
      ramp up stats seperate: false


  Test Basic :
    -
      init user count: 0
      final user count: 200
      hatch rate: 30
      time at load: .5
      fresh procedure stats: false
      ramp up stats seperate: false






LoadRunner Settings:
  RPC Settings:
    port: 80
    endpoint: /LoadServer

  Locust UI Settings:
    port: 8089
    max wait: 1

  Locust Runner Settings:
    port: 5557
    SLA Response Time Cutoff ms: 150
    To Failure Max Consecutive Frames Failed: 3
    To Failure Test Prefix: "To Failure"
    stat reporting interval: 2

  Servers:
    Potential Servers:
      - "0.0.0.0"
      - b-gp2-lgen-8.imovetv.com
      - b-gp2-lgen-9.imovetv.com



DataBase Settings:
  Environments:
    DEV1:
      Host: d-gp2-dbpgdvr1master-1
      Port: 5432
    DEV2:
      Host: d-gp2-dbpgdvr2master-1
      Port: 5432
    DEV3:
      Host: d-gp2-dbpgdvr3master-1
      Port: 5432
    QA:
      Host: q-gp2-dbpgdvr1
      Port: 5432
    BETA:
      Host: b-gp2-dbpgdvr1
      Port: 5432
    BETA2:
      Host: b-gp2-dbpgdvr2
      Port: 5432

  Credentials:
    DataBase Name: dvrcloud
    DataBase Username: dvrcloud
    DataBase Password: dvrcloud_pw

MetaData:
  Environments:
    DEV1:
      VIP Host: d-cg17-dvrmeta.movetv.com
      Node Host: d-gp2-dvrmeta-{0}.imovetv.com
      Total Nodes: 3
    DEV2:
      VIP Host: d-cg17-dvrmeta2-1.movetv.com
      Node Host: d-gp2-dvrmeta2-{0}.imovetv.com
      Total Nodes: 2
    DEV3:
      VIP Host: d-cg17-dvrmeta3.movetv.com
      Node Host: d-gp2-dvrmeta3-{0}.imovetv.com
      Total Nodes: 3
    QA:
      VIP Host: q-cg17-dvrmeta.movetv.com
      Node Host: q-gp2-dvrmeta-{0}.imovetv.com
      Total Nodes: 3
    BETA:
      VIP Host: b-cg17-dvrmeta.movetv.com
      Node Host: b-gp2-dvrmeta-{0}.imovetv.com
      Total Nodes: 3
    BETA2:
      VIP Host: b-cg17-dvrmeta2.movetv.com
      Node Host: b-gp2-dvrmeta2-{0}.imovetv.com
      Total Nodes: 3


  API Prefix: /mds/v{version}/{suf}/
  Routes:

    Get Asset Json:
      Route: asset/{0}.json
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: false
      Version 1:
        Required Fields: null
        Optional Fields: null

    Get Asset Jpeg:
      Route: asset/{0}.jpg
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: false
      Version 1:
        Required Fields: null
        Optional Fields: null

    Load Asset:
      Route: asset
      Versions: [1]
      Normal Min: 30
      Normal Max: 50
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields: null

    Get Airing:
      Route: airing
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rs_recspace: int
          inactive: bool
          allow_auto_delete: bool
          description: string
          subscription_key: int-l
          prepad: int
          postpad: int

    Load Airing:
      Route: airing
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
          channel: {arg2: channel_id, pos: 1}
          asset: {arg3: asset_id, pos: 2}
        Optional Fields:
          prepad: int
          postpad: int
          lsdvr: guid
          protected: bool

  Extra Host Routes:



RecAPI:
  Environments:
     DEV1:
      VIP Host: d-cg17-dvrapi.movetv.com
      Node Host: d-gp2-recapi-{0}.imovetv.com
      Total Nodes: 2
     DEV2:
      VIP Host: d-cg17-dvrapi2-1.movetv.com
      Node Host: d-gp2-dvrapi2-{0}.imovetv.com
      Total Nodes: 6
     DEV3:
      VIP Host: d-cg17-dvrapi3-1.movetv.com
      Node Host: d-gp2-dvrapi3-{0}.imovetv.com
      Total Nodes: 6
     QA:
      VIP Host: q-cg17-dvrapi.movetv.com
      Node Host: q-gp2-recapi-{0}.imovetv.com
      Total Nodes: 2
     BETA:
      VIP Host: b-cg17-recapi.movetv.com
      Node Host: b-gp2-recapi-{0}.b.movetv.com
      Total Nodes: 6
     BETA2:
      VIP Host: b-cg17-dvrapi2.b.movetv.com
      Node Host: b-gp2-dvrapi2-{0}.imovetv.com
      Total Nodes: 2

## This information should match the information listed at
# https://wiki.movenetworks.com/display/RSCLOUD/DVR+Client+APIs
  API Prefix: /rec/v{version}/{suf}/

  Routes:

    User Recordings Ribbon:
      Route: user-recordings
      Versions: [1, 2, 4, 5]
      Normal Min: 1
      Normal Max: 5
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rec_guid: guid
          type: [recently_recorded, recorded_by_name, pending_by_name, pending_by_date, small]
          page_size: int
          page_number: int
          watched: bool
          ribbon_type: [rs, ls, both]
      Version 2:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rec_guid: guid
          type: [recently_recorded, recorded_by_name, pending_by_name, pending_by_date, small]
          page_size: int
          page_number: int
          watched: bool
          ribbon_type: [rs, ls, both]
      Version 4:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rec_guid: guid
          type: [recently_recorded, recorded_by_name, pending_by_name, pending_by_date, small]
          page_size: int
          page_number: int
          watched: bool
          ribbon_type: [rs, ls, both]
      Version 5:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rec_guid: guid
          type: [recently_recorded, recorded_by_name, pending_by_name, pending_by_date, small]
          page_size: int
          page_number: int
          watched: bool
          ribbon_type: [rs, ls, both]


    User Franchise Ribbon:
      Route: user-franchise-recordings
      Versions: [1, 4]
      Normal Min: 10
      Normal Max: 30
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
          franchise: {arg2: franchise, pos: 1}
        Optional Fields:
          filter: [all, pending, recorded]
          watched: bool
          ribbon_type: [rs, ls, both]
      Version 4:
        Required Fields:
          user: {arg1: guid, pos: 0}
          franchise: {arg2: franchise_guid, pos: 1}
        Optional Fields:
          filter: [all, pending, recorded]
          watched: bool
          ribbon_type: [rs, ls, both]


    User Recspace Information:
      Route: user-recspace
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields: null


    Update User Settings:
      Route: user-update
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields:
          rs_recspace: int
          inactive: bool
          allow_auto_delete: bool
          description: string
          subscription_key: int-l
          prepad: int
          postpad: int


    Create Recordings:
      Route: rec-create
      Versions: [1, 4]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
          channel: {arg2: channel_id, pos: 1}
          asset: {arg3: asset_id, pos: 2}
        Optional Fields:
          prepad: int
          postpad: int
          lsdvr: guid
          protected: bool
      Version 4:
        Required Fields:
          user: {arg1: guid, pos: 0}
          channel: {arg2: guid, pos: 1}
          external_id: {arg3: external_id, pos: 2}
        Optional Fields:
          prepad: int
          postpad: int
          lsdvr: guid
          protected: bool


    Protect Recordings:
      Route: rec-save
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          type: [rs, ls]
          guid: {arg1: guid, pos: 0}
        Optional Fields:
          protected: bool


    Mark Watched:
      Route: rec-watched
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          type: [rs, ls]
          guid: {arg1: guid, pos: 0}
        Optional Fields: null


    Delete Recordings:
      Route: rec-delete
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          type: [rs, ls]
          guid: {arg1: guid, pos: 0}
        Optional Fields: null


    Create Rules:
      Route: rule-create
      Versions: [1, 4]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
          type: [franchise]
          franchise: [377898, 216]
          mode: [new, all]
        Optional Fields:
          title: string
          keep: int
          protected: bool
      Version 4:
        Required Fields:
          user: {arg1: guid, pos: 0}
          type: [franchise]
          franchise: [baee73e6-1dc4-4b89-9e06-94ede7decc25, 3613ee7e-b193-4be4-a60b-bb2fb116e61c]
          mode: [new, all]
        Optional Fields:
          title: string
          keep: int
          protected: bool

    Update Rules:
      Route: rule-update
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          guid: {arg1: guid, pos: 0}
          type: [franchise]
        Optional Fields:
          protected: bool
          title: string
          mode: [new, all]
          keep: int

    Delete Rules:
      Route: rule-delete
      Versions: [1]
      Normal Min: null
      Normal Max: null
      List: true
      Version 1:
        Required Fields:
          guid: {arg1: guid, pos: 0}
          type: [franchise]
        Optional Fields:
          purge: bool

    List Rules:
      Route: user-recrules
      Versions: [1, 4]
      Normal Min: 2
      Normal Max: 7
      List: false
      Version 1:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields: null
      Version 4:
        Required Fields:
          user: {arg1: guid, pos: 0}
        Optional Fields: null


  Extra Host Routes:
    - Nothing
    - Redundant Ts Segment
    - Basic Network
    - Network Byte Size
    - Small Db
    - Large Db
    - Nginx Check
    - Bind Recording

Playback Settings:
  Playback Routes:
    - Playback
    - Top N Playback

  Playback Players:
    - HLS
    - DASH
    - QMX









